#!/usr/bin/env node
/* Turns the transcribed governance corpus into SQL for governance_document and
   governance_finding (migration 0009).

     node supabase/governance/build-seed.mjs <corpus dir> > supabase/governance/seed.sql
     psql "$DATABASE_URL" -f supabase/governance/seed.sql     # or paste into the SQL editor

   The corpus directory is the transcription the brief cites
   (`MBC_Bylaws:Policies:Procedures/`): one Markdown file per document, and
   DISCREPANCY-DOCKET.md beside them. Nothing here is edited through the API;
   re-run the loader when the transcription changes and the upserts replace
   what is there by slug and by finding number.

   How a file is read:
     - the slug is the file name, lower-cased, non-alphanumerics to hyphens
     - the title is the first `# ` heading, else the file name
     - the code is a leading "A009" / "D002" style tag, or "Art. II" for a file
       whose name or title begins with "Article"; else empty
     - the kind is `policy` for a lettered code, `bylaws` for an article, and
       `procedure` for anything under a directory named procedures
     - documents sort by their code, then by file name
   The docket is split on headings that begin with a number ("## 8", "### 8.",
   "## Finding 8"); the rest of the heading is the finding's title, the text
   below it is the body, and every "Art. …" or lettered-code citation in the
   body is collected into `cites`. */

import { readdirSync, readFileSync, statSync } from 'node:fs'
import { basename, extname, join, relative } from 'node:path'

const root = process.argv[2]
if (!root) {
  console.error('usage: build-seed.mjs <corpus dir>')
  process.exit(2)
}

const files = []
const walk = (dir) => {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name)
    if (statSync(path).isDirectory()) walk(path)
    else if (['.md', '.markdown', '.txt'].includes(extname(name).toLowerCase())) files.push(path)
  }
}
walk(root)

const q = (value) => "'" + String(value).replace(/'/g, "''") + "'"
const arr = (values) => 'array[' + (values.length ? values.map(q).join(', ') : '') + ']::text[]'

const CITE = /\b(?:Art\.\s*[IVX]+(?:\.[A-Z])?(?:\s*§\s*\d+)?(?:\s*¶\s*\d+)?|[A-Z]\d{3}(?:\s*§\s*\d+)?)/g

const documents = []
const findings = []

for (const path of files.sort()) {
  const text = readFileSync(path, 'utf8')
  const name = basename(path, extname(path))
  const isDocket = /discrepancy[-_ ]?docket/i.test(name)
  if (isDocket) {
    const parts = text.split(/^(#{1,3}\s*(?:finding\s*)?\d+[.:)\s-].*)$/im)
    for (let i = 1; i < parts.length; i += 2) {
      const heading = parts[i]
      const body = (parts[i + 1] ?? '').trim()
      const number = Number(/(\d+)/.exec(heading)[1])
      const title = heading.replace(/^#{1,3}\s*(?:finding\s*)?\d+[.:)\s-]*/i, '').trim() || 'Finding ' + number
      const cites = [...new Set((body.match(CITE) ?? []).map((c) => c.replace(/\s+/g, ' ')))]
      findings.push({ number, title, body, cites, status: /^\s*(?:\*\*)?status(?:\*\*)?\s*[:—-]\s*(?:\*\*)?resolved/im.test(body) ? 'resolved' : 'open' })
    }
    continue
  }
  const titleMatch = /^#\s+(.+)$/m.exec(text)
  const title = (titleMatch ? titleMatch[1] : name).trim()
  const codeMatch = /^([A-Z]\d{3})\b/.exec(name) || /^([A-Z]\d{3})\b/.exec(title)
  const articleMatch = /^Article\s+([IVX]+)/i.exec(name.replace(/[_-]/g, ' ')) || /^Article\s+([IVX]+)/i.exec(title)
  const code = codeMatch ? codeMatch[1] : articleMatch ? 'Art. ' + articleMatch[1].toUpperCase() : ''
  const inProcedures = /(^|[\\/])procedures?([\\/]|$)/i.test(relative(root, path))
  const kind = inProcedures ? 'procedure' : articleMatch ? 'bylaws' : 'policy'
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
  documents.push({ slug, kind, code, title, body: text.trim(), file: name })
}

documents.sort((a, b) => (a.code || 'zzz').localeCompare(b.code || 'zzz') || a.file.localeCompare(b.file))

const out = []
out.push('-- Generated by supabase/governance/build-seed.mjs. Re-run it; do not edit.')
out.push('begin;')
documents.forEach((d, index) => {
  out.push(
    `insert into governance_document (slug, kind, code, title, body, position) values (${q(d.slug)}, ${q(d.kind)}, ${q(d.code)}, ${q(d.title)}, ${q(d.body)}, ${(index + 1) * 10})` +
      ` on conflict (slug) do update set kind = excluded.kind, code = excluded.code, title = excluded.title, body = excluded.body, position = excluded.position, updated_at = now();`,
  )
})
findings.sort((a, b) => a.number - b.number).forEach((f) => {
  out.push(
    `insert into governance_finding (number, title, body, cites, status) values (${f.number}, ${q(f.title)}, ${q(f.body)}, ${arr(f.cites)}, ${q(f.status)})` +
      ` on conflict (number) do update set title = excluded.title, body = excluded.body, cites = excluded.cites, status = excluded.status;`,
  )
})
out.push('commit;')
process.stdout.write(out.join('\n') + '\n')
console.error(`${documents.length} documents, ${findings.length} findings`)
